### ISSUE TITLE
^M at the end of some of the lines.

### ISSUE THREAD

**Issue by opsdisk** [laconicwolf/Python-AWS#1]
Hey,

Just noticed it when browsing through the code on this specific script...may be in others.

https://github.com/laconicwolf/Python-AWS/blob/9b22183e485ff28e96a2044e5e333973d4bc05eb/create_ec2_instance.py#L17

![capture](https://user-images.githubusercontent.com/8660252/43359220-68acc800-9264-11e8-9f46-58fc1b1904a6.PNG)

**Comment by laconicwolf** [comment]
Thanks. I'm guessing it's because I'm writing these on Windows. This scripts run for me on Windows despite this. I'll try on Linux later and see if it's causing problems.

**Comment by opsdisk** [comment]
There's a dos2unix utility in Linux that converts them automatically if you want to go down that route.

**Comment by laconicwolf** [comment]
Yep. Thanks. I'm guessing it's just a setting in PyCharm dealing with line endings. I do think it's strange that the ^M only appears on and after the line using a '\' to break up a long line. I figured GitHub would account for things like that. Either way, I'll see if adjusting my lie ending settings and see what happens. As of now, I cloned it in windows and linux and the code ran fine for me.
